//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public int maPhieuNhap { get; set; }
        public int maSP { get; set; }
        public Nullable<int> SLNhap { get; set; }
        public Nullable<decimal> giaNhap { get; set; }
        public Nullable<decimal> thanhTien { get; set; }
    
        public virtual HDNhapSP HDNhapSP { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
