//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.CTTNs = new HashSet<CTTN>();
            this.HDOffLines = new HashSet<HDOffLine>();
            this.HDOnlines = new HashSet<HDOnline>();
            this.HDTraGops = new HashSet<HDTraGop>();
        }
    
        public int MaKH { get; set; }
        public string tenKH { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
        public string email { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public Nullable<decimal> tongMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTN> CTTNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDOffLine> HDOffLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDOnline> HDOnlines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDTraGop> HDTraGops { get; set; }
    }
}
