//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraGop
    {
        public int MaPhieu { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<System.DateTime> NgayDenHan { get; set; }
        public Nullable<int> Ki { get; set; }
        public Nullable<int> MaMucPhat { get; set; }
        public Nullable<decimal> TienDong { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
    
        public virtual HDTraGop HDTraGop { get; set; }
        public virtual Phat Phat { get; set; }
    }
}
