//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTPNs = new HashSet<CTPN>();
            this.CTTonKhoes = new HashSet<CTTonKho>();
        }
    
        public int maSP { get; set; }
        public Nullable<int> maHang { get; set; }
        public Nullable<int> maLoai { get; set; }
        public string tenSP { get; set; }
        public string anh { get; set; }
        public Nullable<decimal> giaSP { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTonKho> CTTonKhoes { get; set; }
        public virtual Hang Hang { get; set; }
        public virtual Loai Loai { get; set; }
    }
}
