//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int id { get; set; }
        public Nullable<int> idGui { get; set; }
        public Nullable<int> idNhan { get; set; }
        public string Mess { get; set; }
    }
}
